[project]
name = "bs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "opencv-contrib-python>=4.11.0.86",
    "pydantic>=2.10.6",
    "toml>=0.10.2",
]
